# name of the software
name: FurBot Discord Bot

project:
    version: 0.1.0
    download_url: https://github.com/Rendyindo/FurBot-Discord

license:
    software: MIT License
    software_url: http://opensource.org/licenses/MIT

    docs: CC BY 3.0
    docs_url: http://creativecommons.org/licenses/by/3.0/

links:
    header:
      - title: GitHub
        url: https://github.com/Rendyindo/FurBot-Discord
      - title: Invite
        url: https://discordapp.com/api/oauth2/authorize?client_id=406419784301936641&permissions=116736&scope=bot
    footer:
      - title: GitHub
        url: https://github.com/Rendyindo/FurBot-Discord
ui:
    header:
        color1: "#080331"
        color2: "#673051"
        trianglify: true

social:
    github:
        user: Rendyindo
        repo: FurBot-Discord
    twitter:
        enabled: false
        via:
        hash:
        account:
    facebook:
        enabled: false
        profileUrl:

analytics:
    google: 

# Build settings
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock