# name of the software
name: Jekyll Bootstrap Doc
# current version of the software
version: 0.1.0
# url of the download button
downloadUrl: https://github.com/allejo/jekyll-docs-theme/releases
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/allejo/jekyll-docs-theme

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/allejo/jekyll-docs-theme
  - title: Issues
    url: https://github.com/allejo/jekyll-docs-theme/issues?state=open

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: mistic100
  repo: jekyll-bootstrap-doc

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: true
  profileUrl:


theme: jekyll-docs-theme